version: '3.8'

services:
  db:
    image: postgres:14.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  
  kafka:
    image: apache/kafka
    ports:
      - 9092:9092